--==============================================================
-- time/92a_backup_before_removal.sql
-- O2C Timesheet Module — copy everything 93 is about to delete
--
-- RUN THIS BEFORE 93_remove_test_data.sql. It is the only undo that exists.
--
-- WHY RE-SEEDING IS NOT AN UNDO
--   90_test_seed.sql does not restore, it recreates. Every key is
--   GENERATED ALWAYS AS IDENTITY, so the new rows get new ids and nothing that
--   referenced the old ones lines up again. It would also put back the very
--   thing 93 removes -- master rows with no Fusion id.
--
--   Flashback is not a plan either: AS OF TIMESTAMP depends on undo retention,
--   which is minutes to hours and not something to discover you needed.
--
-- WHAT IT MAKES
--   A plain copy of each affected table as <name>_BK. Data only -- no
--   constraints, no indexes, no identity. That is deliberate: this is a
--   parachute, not a schema, and restoring is an INSERT SELECT back.
--
-- Re-runnable: an existing _BK is dropped and retaken, so the backup always
-- reflects the state immediately before the run that matters.
--==============================================================
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============================================================
PROMPT Backing up everything 93 will delete
PROMPT ============================================================

DECLARE
  TYPE t_list IS TABLE OF VARCHAR2(40);
  -- Transactions, then the masters 93 filters. Masters are copied WHOLE rather
  -- than filtered: a backup that reasons about which rows mattered is a backup
  -- that can be wrong about it.
  v t_list := t_list(
    'OC_TS_WEEK', 'OC_TS_ENTRY', 'OC_TS_APPROVAL', 'OC_TS_ADJUSTMENT',
    'OC_TS_AUDIT', 'OC_TS_SALARY_HOLD', 'OC_TS_SALARY_HOLD_DAY',
    'OC_TS_MONTH_CONFIRM', 'OC_TS_LEAVE_LOSS_COVER', 'OC_TS_CLIENT_DOC',
    'XX_O2C_TIMESHEET_ACCRUAL_IF',
    'OC_TIME_PROJECT', 'OC_TIME_TASK', 'OC_TIME_ALLOCATION',
    'OC_TIME_CALENDAR', 'OC_TIME_ABSENCE');
  v_n   NUMBER;
  v_tot NUMBER := 0;
BEGIN
  FOR i IN 1 .. v.COUNT LOOP
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || v(i) || '_BK PURGE';
      EXCEPTION WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;   -- -942 = did not exist
      END;

      EXECUTE IMMEDIATE 'CREATE TABLE ' || v(i) || '_BK AS SELECT * FROM ' || v(i);
      EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || v(i) || '_BK' INTO v_n;
      v_tot := v_tot + v_n;
      DBMS_OUTPUT.PUT_LINE(RPAD(v(i) || '_BK', 34) || TO_CHAR(v_n, '9,999,999'));
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(RPAD(v(i) || '_BK', 34)
                        || 'SKIPPED - ' || SUBSTR(SQLERRM, 1, 60));
    END;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(RPAD('-', 46, '-'));
  DBMS_OUTPUT.PUT_LINE(RPAD('total rows copied', 34) || TO_CHAR(v_tot, '9,999,999'));
END;
/

PROMPT
PROMPT ============================================================
PROMPT To restore
PROMPT ============================================================
PROMPT
PROMPT Reverse the delete order -- masters first, then transactions, or every
PROMPT insert fails its foreign key:
PROMPT
PROMPT   INSERT INTO oc_time_project    SELECT * FROM oc_time_project_BK
PROMPT    WHERE project_id NOT IN (SELECT project_id FROM oc_time_project);
PROMPT   ... tasks, allocations, calendar, absences ...
PROMPT   ... then oc_ts_week, oc_ts_entry, and the rest ...
PROMPT
PROMPT The NOT IN guard matters: the sync will have re-inserted some of these
PROMPT rows by the time you restore, and a blind insert collides on the key.
PROMPT
PROMPT IDENTITY COLUMNS. oc_ts_week.ts_week_id and friends are GENERATED
PROMPT ALWAYS, which refuses an explicit value. Restoring those needs
PROMPT   ALTER TABLE x MODIFY (id GENERATED BY DEFAULT AS IDENTITY);
PROMPT before the insert and the same statement back to ALWAYS afterwards.
PROMPT Worth knowing NOW rather than mid-restore.
PROMPT
PROMPT Drop the _BK tables once the rebuild is proven.
